### ISSUE TITLE
Iphone and IPhone recipes

### ISSUE THREAD

**Issue by acornmonkey** [expitau/InfiniteCraftWiki#10]
The recipes listed for Iphone and IPhone actually make iPhone.

**Comment by acornmonkey** [comment]
The entries for the Iphone, IPhone and iPhone need to be merged.

- "pn":["📱","Iphone",11]
- "9y":["📱","IPhone",12]
- "Bb6":["📱","iPhone",13]

The new entry should have the name "iPhone" and cost of 11. I'm not sure what should be done about its identifier though, but I think maybe it should be "Bb6" because there are 26 recipes under that identifier, 9 under "pn" and 3 under "9y". But maybe "pn" should be used due to it being shorter.

**Comment by reumarks** [comment]
huh that is very interesting, for me currently, all of those recipes do craft the same thing, but I get "Iphone" from all of them.
![image](https://github.com/expitau/InfiniteCraftWiki/assets/22671898/58d81edf-6a65-4c6c-a11e-9d54c4bab869)

**Comment by reumarks** [comment]
Looking at the web requests directly in the dev-tools, it seems that the combinations listed on the Wiki are all technically correct in terms of what the server returns, all three capitalizations are possible and return as listed:

![image](https://github.com/expitau/InfiniteCraftWiki/assets/22671898/051c2615-06b5-492a-9ca7-b0b40700ba01)
![image](https://github.com/expitau/InfiniteCraftWiki/assets/22671898/2236c730-e789-429e-b134-ed99ab1cfe82)
![image](https://github.com/expitau/InfiniteCraftWiki/assets/22671898/23ad6fc9-b218-492e-b971-778ada4e2989)

I think this means that there must be some client side similarity validation that only happens in very specific situations like this, that based on the first response that you get, all future responses will be merged into that initial item.

**Comment by acornmonkey** [comment]
I first got iPhone by combining Apple and China. This recipe is not listed under any of the three iPhone elements that get merged.

**Comment by expitau** [comment]
I believe that this works on the translation level, it may be possible that this appears differently in different languages. I'm going to close this as I don't think there any action required for this site
