### ISSUE TITLE
Nothing should have a cost, but it shouldn't have any recipes that use it

### ISSUE THREAD

**Issue by acornmonkey** [expitau/InfiniteCraftWiki#11]
Its cost should be 6, as the crafting recipe shown on https://expitau.github.io/InfiniteCraftWiki/?e=A suggests. I think it's useful to keep track of how many elements are needed to get an invalid recipe.

But the three recipes using Nothing as an ingredient don't make any sense, since it doesn't actually exist as an item in the game.

**Comment by expitau** [comment]
Thanks for your feedback! This is an error in the data, I'll fix it shortly

**Comment by expitau** [comment]
Removed recipes that have "Nothing" as an ingredient
