### ISSUE TITLE
Importing save files breaks because of "+"

### ISSUE THREAD

**Issue by reumarks** [expitau/InfiniteCraftWiki#12]
Due to some sort of encoding in the browser, the current bookmarklet script to denote elements that the user already has and add them to saveData array does not work for any elements that contain a "+" in their encoding.

This is most easily seen with "River", since it is one of the first elements to have a "+" in its elementId. If you have river in Infinite craft, and then import your data into the Wiki, you will notice that river does not appear.

I'm nearly finished a decently sized PR that that adds the importing functionality into the main website directly and then uses that to show much simpler crafting recipes (at the cost of a little bit of loading time, but not actually that bad with some optimizations), so having this fixed would be great since it is a decently noticeable error.

**Comment by expitau** [comment]
Interesting! I look forward to it

**Comment by reumarks** [comment]
Yeah it's great, I'm basically developing the bookmarklet system in a way that is perfectly seamless for the user!
No need to copy and paste anything -- and because of the way that it is implemented, we are able to update all of the functionality just by pushing changes to the repo since the bookmarklet just embeds an Iframe that does all the work, meaning that 99% of the changes we might want to implement won't require them to update the bookmarklet themselves, and we can fix bugs and push new features instantly for everyone.

**Comment by expitau** [comment]
+ in bookmarklet should be fixed in most recent update
