### ISSUE TITLE
Add more recipes

### ISSUE THREAD

**Issue by Jcw87** [expitau/InfiniteCraftWiki#13]
I have my own recipe database, created from my own prodding at the API. I've also gathered recipes from various sources (result was always verified with an API call).
[recipes.zip](https://github.com/expitau/InfiniteCraftWiki/files/14451118/recipes.zip)

Something I've observed while gathering recipes is that, on rare occasions, the recipes can change. I've seen a few recipes that used to work, but now result in "Nothing" (likely intentional censoring), and 1 case of a recipe just getting a completely different result.

**Comment by expitau** [comment]
Thanks for your contribution, your dataset has been merged and pushed to https://expitau.github.io/InfiniteCraftWiki/. You've been acknowledged as a contributor in the README
