### ISSUE TITLE
Recipes I've found

### ISSUE THREAD

**Issue by JumboDS64** [expitau/InfiniteCraftWiki#17]
I'm not really sure how else to contribute new recipes. I tried forking, but I couldn't get the page to work locally and the .json file is too intimidating. Here's some I've found:

New elements:
Ludo + Studio = 🎮 Ludostudio
Ludostudio + Ludo = 🎲 Ludo Studio
Dingo + Blue's Clues = 🐶 Bluey
Blue's Clues + BBC = 🔍 Blue’s Clues & You
Bluey + Dad = 🐶 Bluey's Dad
Bluey's Dad + Stink = 😔 Bluey's Dad Stinks
Bluey's Dad + Married = 🐶 Bluey's Mom
Bluey's Dad + Drunk = 🐶 Bluey's Mum
Bluey's Dad + Alcohol = 🦴 Bluey's Dad's Dad
Bluey + Ludo Studio = 💿 Bluey: The Album
Bluey: The Album + Alice = 👗 Alice Blue Gown
Bluey's Dad + Bluey's Mum = Bluey
Bluey's Dad + Bluey's Mom = Bluey
Bluey's Dad + Princess = Bluey
Bluey's Dad + Fairy = Bluey
Bluey's Mum + Blue Smoke = Bluey
Bluey's Mum + Dandelion = Bluey
Bluey's Mom + Bluey's Mum = Bluey's Mum

Existing elements:
Bluey + Mom = Dad
Bluey + Prince = Blue Prince
Bluey + Mummy = Daddy
Bluey + Happiness = Smurf
Bluey + Peter Pan = Tinkerbell
Bluey + Smoke = Blue Smoke
Bluey + Blue Smoke = Blueberry
Bluey + Incense = Smoke
Bluey + Dandelion = Dandelion
Bluey + Princess = Prince
Bluey + Flower = Bluebell
Bluey + Bluebell = Blueberry
Bluey + Flatulence = Blue Flame
Bluey + Flat = Pancakes
Bluey + Flash = Lightning
Bluey + Friendship = Bingo
Bluey's Dad + Incense = Smoke
Bluey's Dad + Dating = Married
Bluey's Dad + Smurf = Papa Smurf
Bluey's Dad + Adobe = Brick
Blue Prince + Happiness = Smurf
Smurf + Captain Hook = Peter Pan
Ludo Studio + Prince = Prince of Persia
Alice Blue Gown + Animation = Disney
Purple + Smurf = Barney

My interests are probably rather evident, lol. Also, Wind's emoji should be 🌬️, not 💨.

**Comment by expitau** [comment]
Thanks for using the project! Unfortunately, I am no longer actively maintaining the list of recipes, as I am busy with exams. If you are able to figure out how to update the data and submit a pull request, I am happy to review it, but it is quite complicated unfortunately. There is some work in https://github.com/expitau/InfiniteCraftWiki/pull/14 for importing your data, but it is currently incomplete and abandoned due to lack of time.
