### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by theeternalsw0rd** [expitau/InfiniteCraftWiki#18]
There seems to be some human modifications or the AI training has changed to the point that some recipes are no longer working. I don't want to say exactly what as it likely would get me and potentially the project flagged. I'll just say it is the label for the culprits related to bush, towers, and jets. There are a bunch of listed recipes. I tried about 20 before stopping. The target word may have been removed as a possible output entirely, or I was just unlucky in my attempts. The primary culprit's full name also seems to be inaccessible at least via the recipes not involving the earlier target which I can't use. The first name is still accessible.

**Comment by theeternalsw0rd** [comment]
According to another repository of recipes, there has been a censor added by the game creator. I did run into another two words that are unavailable and there are more out there. From what I've read, the censored words can be added manually to an import and work with subsequent recipes that use the censored word and I'll be testing this over the next day. I'll report back my findings.

**Comment by expitau** [comment]
Some recipes were fixed in https://github.com/expitau/InfiniteCraftWiki/pull/20, does this solve your issue?

**Comment by expitau** [comment]
Stale. Please reopen if needed
