### ISSUE TITLE
Erroneous Recipes

### ISSUE THREAD

**Issue by Jcw87** [expitau/InfiniteCraftWiki#19]
I performed a comparison between my recipe database and yours, and found some interesting differences.

1. You have several recipes that create an item beginning with a space. There was a brief period in time where the Infinite Craft API was returning these erroneous results. Attempting to craft these recipes today will give you the same result without the leading space.
2. There are several recipes that appear as if a CSV parsing issue occurred when importing them. Example: `Rice Krispies` + `Scent` = `Snap, Crackle, Pop`, but your database shows `Snap`. I initially thought these may have been caused while importing my recipes, but these errors existed before my contribution.
3. There are several ingredient combinations that appear multiple times with different results. Example: `Bacteria` + `Spill` has at least 4 results: `Punch`, `Venus Flytrap`, `Daenerys`, `Philosopher’s Stone`

You can see all of these differences in the CSV file below. I tried to exclude differences caused by censored words.
[verify_result.csv](https://github.com/expitau/InfiniteCraftWiki/files/14899162/verify_result.csv)

I am not asserting that all of my recipes are correct, only that they are different. Use your best judgement on resolving these.

**Comment by expitau** [comment]
Thanks for noticing this. I'm very busy for the next couple weeks so I won't be able to fix this immediately, but if you are able to create a pull request that updates the data.json file I will merge it
