### ISSUE TITLE
Sync With Wiki bookmarklet not working

### ISSUE THREAD

**Issue by MeddyIka** [expitau/InfiniteCraftWiki#23]
As of 5/12/2024, it seems that the Sync With Wiki function isn't working as it should. It's not opening the Infinite Craft Wiki page, just reads 'Syncing with Wiki' at top.

**Comment by expitau** [comment]
Thanks for the feedback! I'll take a look

**Comment by expitau** [comment]
It should be updated now, please refresh and update the bookmarklet (delete the bookmarklet, and drag to your bookmarklet bar again)
